<?php
/**
 * Created by PhpStorm.
 * User: lars.peeters
 * Date: 18/02/2015
 * Time: 16:08
 */

/**
 * Implements hook_menu().
 */
function landing_page_menu()
{
    $items = array();


    $items['calculations'] = array(
        'title' => 'Bruto-netto',
        'page callback' => "index",
        'access callback' => true,
        'access arguments' => array("view"),
        'file' => 'includes/benefitonline_calculations_form.inc',
        'expanded' => true,
        'menu_name' => 'main-menu',
        'type' => MENU_NORMAL_ITEM,
        'weight' => 2
    );


    return $items;
}


/**
 * Implements hook_views_api().
 */
function landing_page_views_api()
{
    return array(
        'api' => 3,
    );
}

/**
 * Implements hook_theme_registery_alter().
 */
function landing_page_theme_registry_alter(&$theme_registry) {
    // Defined path to current module.
    $module_path = drupal_get_path('module', 'landing_page');
    // Find all .tpl.php files in this module's folder recursively.
    $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path . '/templates');
    // Itterate through all found template file objects.
    foreach ($template_file_objects as $key => $template_file_object) {
        // If the template has not already been overridden by a theme.
        if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
            // Alter the theme path and template elements.
            $theme_registry[$key]['theme path'] = $module_path;
            $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
            $theme_registry[$key]['type'] = 'module';
        }
    }
}

function landing_page_ctools_plugin_api($module, $api) {
    if ($module == 'page_manager' && $api == 'pages_default') {
        return array('version' => 1);
    }
}